# Generated by Django 3.0.8 on 2020-08-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPerritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='null', upload_to=''),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(max_length=110),
        ),
    ]
